In [1]:
import numpy as np

In [2]:
scores = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
scores

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
y = np.array([1, 1, 2])
correct_scores = scores[range(3), y]
correct_scores

array([2, 5, 9])

In [4]:
correct_scores[:, np.newaxis]

array([[2],
       [5],
       [9]])

In [5]:
scores - correct_scores[:, np.newaxis]

array([[-1,  0,  1],
       [-1,  0,  1],
       [-2, -1,  0]])